name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Close version
        run: ./scripts/version/closeVersion.sh
      - name: Git push closed version
        run: git add gradle.properties && git commit -m "Closed release `./scripts/version/getVersion.sh`" && git push
      - name: Publish package
        run: ./gradlew clean check test build publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare next SNAPSHOT version
        run: ./scripts/version/increaseVersion.sh
      - name: Git push closed version
        run: git add gradle.properties && git commit -m "Created new snapshot version `./scripts/version/getVersion.sh`" && git push
