name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Close version
        run: |
          ./scripts/version/closeVersion.sh
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gradle.properties
          git commit -m "Closed release `./scripts/version/getVersion.sh`"
      - name: Publish package
        run: chmod +x gradlew && ./gradlew clean check test build publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare next SNAPSHOT version
        run: |
          ./scripts/version/increaseVersion.sh
          git add gradle.properties
          git commit -m "Created new snapshot version `./scripts/version/getVersion.sh`"
      - name: Git push version
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}